#!/usr/bin/env sh

# Chore is a tiny task runner with some pre-defined commands.

set -e

GIT_URL="https://github.com/matanlurey/pub.lurey.dev"
GIT_REF="40e3dbb2a7b4eee34238f0f9736312b1e6d18dc3"

# Silently activate the pinned version of `chore.dart` from GitHub.
# Only print if there is an error.
dart pub global activate -sgit $GIT_URL --git-path packages/chore --git-ref=$GIT_REF 2>&1 > /dev/null

# Now run and forward arguments and the output.
dart pub global run chore "$@"
