# Format: https://dart.dev/tools/pub/pubspec

name: package
version: 0.0.0
environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.14.0

dev_dependencies:
  args: ^2.5.0
  checks: ^0.3.0
  chore:
    git:
      url: https://github.com/matanlurey/chore.dart.git
  coverage: ^1.7.2
  oath: ^0.2.0
  path: ^1.9.0
  test: ^1.25.3
