# Format: https://dart.dev/tools/pub/pubspec

name: package

# UNCOMMENT THESE TO PUBLISH TO PUB.
# description: |-
#   A description of the package.
# version: 0.0.0
# repository: https://github,com/matanlurey/package

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  checks: ^0.3.0
  oath: ^0.2.2
  test: ^1.25.14
