# Format: https://dart.dev/tools/pub/pubspec

name: package
version: 0.0.0
environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.14.0

dev_dependencies:
  checks: ^0.3.0
  oath: ^0.2.0
  test: ^1.25.3
