name: Deploy

on:
  # Post-submit.
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dart-lang/setup-dart@v1.6.4
      - run: dart pub get
      - name: Build API Docs
        run: ./chore dartdoc
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/api
  # publish:
  #   if: github.event_name == 'push'
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4.2.0
  #     - uses: dart-lang/setup-dart@v1.6.5
  #     - run: dart pub get
  #     - run: ./chore publish
  #       env:
  #         PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
